### ISSUE TITLE
error en nombre de campo giro

### ISSUE THREAD

**Issue by rapolebas** [dansanti/l10n_cl_dte#16]
Dice "parnter_id" 

https://github.com/dansanti/l10n_cl_dte/blob/2da3999e12282b0ff20e23d74f9a65c8efca0672/views/layout.xml#L107

Saludos

**Comment by dansanti** [comment]
hola, por favor indicar la versión de odoo, y más detalles, no se entiende..

**Comment by rapolebas** [comment]
Hola, la version es la 9.0 , en esa linea el campo que llama dice  "parnter_id" debiese decir "partner_id".

Saludos
