### ISSUE TITLE
Factura XML sin Tasa IVA

### ISSUE THREAD

**Issue by ccataldov** [dansanti/l10n_cl_dte#8]
Estimado Daniel.
Primero que todo felicitar por los avances logrados en Facturación Electrónica.
Mi problema es el siguiente:
El XML resultante de la factura afecta no tiene declarado IVA y aparece como exento. La factura PDF es correcta con IVA incluido.
Adjunto pantallazo XML:
![2017-05-10-033547_1296x698_scrot](https://cloud.githubusercontent.com/assets/16226945/25886044/36931b2a-3532-11e7-89b7-923e379934a5.png)
De antemano gracias.
Saludos.

**Comment by dansanti** [comment]
Hola! 

por este tipo de consutas por favor abrir un tema en el foro en odoocoop.cl o globalresponse.cl.

El asunto es que en el mantenedor de impuestos debes agregaar el código 14 al iva
